# -*- coding: utf-8 -*-
"""Tarea1Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AnXIW6nKx9b4xKHRpRgw7yt3aHrACOa6
"""

print("Hello world")
name=input("cual es su nombre? ")
print("Hola" , name)

print("/////////////////////////////////////////////////")
print("/////////////////////////////////////////////////")

a = float(input ("Ingrese su altura en metros "))
peso = float(input("ingrese su peso actual: "))
p = float((24*a*a))
if(peso>p):
  print("Su peso deberia ser: " , p , ", gordo")
elif(peso<p):
  print("Su peso deberia ser: " , p , ", desgalamido")
else:
  print("tu peso es perfecto" )
  



print("/////////////////////////////////////////////////")
print("/////////////////////////////////////////////////")

uno = int(input("Ingrese el valor desde el cual quiere que inicie el intervalo: ")) 
dos = int(input("Ingrese el valor hasta donde quiere que termine el intervalo: ")) 
if(uno>dos):
    print("ERORR, el primer numero es mayor al segundo")
else:
    for i in range(uno,dos+1):
        print(i)

print("/////////////////////////////////////////////////")
print("/////////////////////////////////////////////////")

from datetime import datetime
dHoy = (datetime.today().isoweekday())
if(dHoy==2 or dHoy==4):
    print("Hoy hay clase")
else:
    print("Hoy no hay clase")

print("/////////////////////////////////////////////////")
print("/////////////////////////////////////////////////")

contrasena = input("ingrese su contraseña: ")

while True:
  entrada = input("ingrese la contraseña: ")
  if (entrada==contrasena or entrada=="exit"):
    break